########################################################################################################################
### - PASSWORD CHANGE (admin)

POST {{host}}/api/auth/password
Content-Type: application/json

{
  "login": "admin",
  "password": "password",
  "secret" : "secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
});
%}

########################################################################################################################
### - PASSWORD CHANGE (patiento)

POST {{host}}/api/auth/password
Content-Type: application/json

{
  "login": "patiento",
  "password": "PATIENTO",
  "secret" : "patiento"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
});
%}


########################################################################################################################
### - SECRET CHANGE

POST {{host}}/api/auth/secret
Content-Type: application/json

{
  "login": "patiento",
  "password": "PATIENTO",
  "secret" : "PATIENTO"
}

}


