########################################################################################################################
### - LOGIN (admin)

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
  client.global.set("token", response.body.token);
});
%}

########################################################################################################################
### - LOGIN (manager)

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "login": "manager",
  "password": "manager"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
  client.global.set("token", response.body.token);
});
%}

########################################################################################################################
### - LOGIN  (doctor)

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "login": "doctor",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
  client.global.set("token", response.body.token);
});
%}

########################################################################################################################
### - LOGIN  (patient)

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "login": "patient",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
  client.global.set("token", response.body.token);
});
%}

########################################################################################################################
### - LOGIN  (patiento - new)

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "login": "patiento",
  "password": "PATIENTO"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Response Content-Type is not application/json");
  client.global.set("token", response.body.token);
});
%}

########################################################################################################################
### - LOGOUT

POST {{host}}/api/auth/logout
Content-Type: application/json
Authorization: {{token}}

########################################################################################################################
